spring.application.name=secure-file-sharing-platform

spring.datasource.url=jdbc:postgresql://postgres:5432/filesharingdb
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

file.upload-dir=/app/uploads