spring.application.name=secure-file-sharing-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/filesharingdb
spring.datasource.username=postgres
spring.datasource.password=souha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true