services:
  postgres:
    image: postgres:17
    container_name: filesharing-postgres
    environment:
      POSTGRES_DB: filesharingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: filesharing-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - file_storage:/app/uploads
    depends_on:
      - postgres

volumes:
  postgres_data:
  file_storage: